Loading Llama 2...
[W socket.cpp:436] [c10d] The server socket has failed to bind to [::]:29500 (errno: 98 - Address already in use).
[W socket.cpp:436] [c10d] The server socket has failed to bind to 0.0.0.0:29500 (errno: 98 - Address already in use).
[E socket.cpp:472] [c10d] The server socket has failed to listen on any local network address.
Traceback (most recent call last):
  File "/pfs/proj/nobackup/fs/projnb10/hpc2n2023-115/env/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/pfs/proj/nobackup/fs/projnb10/hpc2n2023-115/env/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/pfs/proj/nobackup/fs/projnb10/hpc2n2023-115/env/lib/python3.10/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/pfs/proj/nobackup/fs/projnb10/hpc2n2023-115/env/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/pfs/proj/nobackup/fs/projnb10/hpc2n2023-115/env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/pfs/proj/nobackup/fs/projnb10/hpc2n2023-115/env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 255, in launch_agent
    result = agent.run()
  File "/pfs/proj/nobackup/fs/projnb10/hpc2n2023-115/env/lib/python3.10/site-packages/torch/distributed/elastic/metrics/api.py", line 124, in wrapper
    result = f(*args, **kwargs)
  File "/pfs/proj/nobackup/fs/projnb10/hpc2n2023-115/env/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 736, in run
    result = self._invoke_run(role)
  File "/pfs/proj/nobackup/fs/projnb10/hpc2n2023-115/env/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 871, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "/pfs/proj/nobackup/fs/projnb10/hpc2n2023-115/env/lib/python3.10/site-packages/torch/distributed/elastic/metrics/api.py", line 124, in wrapper
    result = f(*args, **kwargs)
  File "/pfs/proj/nobackup/fs/projnb10/hpc2n2023-115/env/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 705, in _initialize_workers
    self._rendezvous(worker_group)
  File "/pfs/proj/nobackup/fs/projnb10/hpc2n2023-115/env/lib/python3.10/site-packages/torch/distributed/elastic/metrics/api.py", line 124, in wrapper
    result = f(*args, **kwargs)
  File "/pfs/proj/nobackup/fs/projnb10/hpc2n2023-115/env/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 546, in _rendezvous
    store, group_rank, group_world_size = spec.rdzv_handler.next_rendezvous()
  File "/pfs/proj/nobackup/fs/projnb10/hpc2n2023-115/env/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/static_tcp_rendezvous.py", line 54, in next_rendezvous
    self._store = TCPStore(  # type: ignore[call-arg]
RuntimeError: The server socket has failed to listen on any local network address. The server socket has failed to bind to [::]:29500 (errno: 98 - Address already in use). The server socket has failed to bind to 0.0.0.0:29500 (errno: 98 - Address already in use).
srun: error: b-cn1601: task 0: Exited with exit code 1
